package com.project.back_end.models;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

@Entity
public class Admin {

// @Entity annotation:
//    - Marks the class as a JPA entity, which means it represents a table in the database.
//    - It is required for persistence frameworks like Hibernate to map the class to a database table.
// 1. 'id' field:
//    - Type: private Long
//    - Description: 
//      - Represents the unique identifier for the Admin entity.
//      - This field is auto-generated by the database using @GeneratedValue with strategy GenerationType.IDENTITY.
//      - It is the primary key of the entity, identified by @Id annotation.

/*id: INT, Primary Key, Auto Increment
- first_name: VARCHAR(50), NOT NULL
- laste_name: VARCHAR(50), NOT NULL
- phone : VARCHAR(13)
- eamil: VARCHAR(50)
- date_of_birth:DATE(),NOT NULL
- adresse : VARCHAR(100), NOT NULL
- grade : VARCHAR(20)
- password: VARCHAR(100), NOT NULL */
@Id
@GeneratedValue(strategy=GenerationType.IDENTITY)
private Long id;

@NotNull
@Size(min=3, max=100)
private String firstName;

@NotNull
@Size(min=3, max=100)
private String lastName;

@Email
private String email;

@Pattern(regexp = "^\\+?[1-9]\\d{1,14}$",
        message = "Numéro de téléphone invalide (format international requis)")
private String phone;
@NotNull
@Past
private String birthDate; 

@Pattern(regexp="^[0-9]{1,5}\s[A-Za-zÀ-ÿ0-9\s,'-]+(?:,\s?[A-Za-zÀ-ÿ\s'-]+)*(?:,\s?[0-9]{4,6})?$",
         message="No valide adresse")
@NotNull
private String adresse;

@NotNull
@Size(min=3, max=50)
private String grade;

@Size(min = 6)
@JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
private String password;

// 2. 'username' field:
//    - Type: private String
//    - Description: 
//      - Represents the username of the admin.
//      - Used to log into the system.
//      - @NotNull validation ensures that this field cannot be null when creating or updating an Admin.
// 3. 'password' field:
//    - Type: private String
//    - Description: 
//      - Represents the password of the admin for authentication.
//      - The field is marked with @JsonProperty(access = JsonProperty.Access.WRITE_ONLY) to prevent the password from being exposed in JSON responses.
//      - @NotNull validation ensures the password cannot be null when creating or updating an Admin.
// 4. Constructor(s):
//    - A no-argument constructor is implicitly provided, required by JPA for entity creation.
//    - A parameterized constructor can be added as needed.
// 5. Getters and Setters:
//    - Standard getter and setter methods are provided for accessing and modifying the fields.
}
